const taskSchemea = new Schema(
    {
        id:{
           type:Number,
           required:true,
        },
        name:{
            type:String,
            required:true
        },
        date:{
            type:Date,
            required:true
        },
        isCompleted:{
            type:Boolean,
            required:true
        }
    }
)